
application: tgif-guestbook
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: mod9.APP

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"